apiVersion: api/v1
kind: Deployment
metadata:
  name: encogestion_api
  namespace: my-kubernetes-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: encogestion_api
  template:
    metadata:
      labels:
        app: encogestion_api
    spec:
      containers:
        - name: encogestion_api
          image: my-docker-registry-encogestion_api:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://dpg-cpue6ruehbks73efid30-a.oregon-postgres.render.com:5432/encogestion_db
            - name: SPRING_DATASOURCE_USERNAME
              value: encogestion_db_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: ZhXJ51Id3XodaGiBiZGbDP3AQVlUVnHq
